[package]
name = "compliments-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
axum-server = "0.7.2"
rand = "0.9.0"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["cors"] }
