[package]
name = "front"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
serde_json = "1.0.140"
wasm-bindgen-futures = "0.4.50"
serde = "1.0.219"
gloo-net = "0.6.0"
